  version: '3.8'

  services:
    prometheus:
      image: prom/prometheus:latest
      container_name: prometheus
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml
      ports:
        - "9090:9090"
      extra_hosts:
        - "host.docker.internal:host-gateway"

    grafana:
      image: grafana/grafana:latest
      container_name: grafana
      ports:
        - "3000:3000"
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=admin
      depends_on:
        - prometheus
      volumes:
        # Montiamo il file del datasource
        - ./grafana/provisioning/datasource/datasource.yml:/etc/grafana/provisioning/datasources/datasource.yml
        # Montiamo il file del provider delle dashboard
        - ./grafana/provisioning/dashboard/dashboard_provider.yml:/etc/grafana/provisioning/dashboards/dashboard_provider.yml
        # Montiamo la cartella che conterrà i file JSON dei grafici
        - ./grafana/dashboard:/etc/grafana/provisioning/dashboards/json_files