apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    # Usa il nome del servizio definito nel docker-compose e la porta 9090
    url: http://prometheus:9090
    isDefault: true
    editable: false